initial_conditions:
  agent1:
    x: 0.0
    y: 0.0
    z: 0.5
    yaw: 0.0
  agent2:
    x: 4.0
    y: 0.0
    z: 0.5
    yaw: 0.0
  agent3:
    x: 1.0
    y: 3.0
    z: 0.5
    yaw: 0.0
  # agent4:
  #   x: 2.0
  #   y: 6.0
  #   z: 0.5
  #   yaw: 0.0
  # agent5:
  #   x: 3.0
  #   y: 2.0
  #   z: 0.5
  #   yaw: 0.0