TASK_1:
  EDGE: [1, 2]
  TYPE: "formation_predicate"
  CENTER: [-1.0, -1.0]
  EPSILON: 1.5
  TEMP_OP: "AlwaysOperator"
  INTERVAL: [30, 50]
  INVOLVED_AGENTS: [1, 2]

TASK_2:
  EDGE: [1, 3]
  TYPE: "epsilon_position_closeness_predicate"
  CENTER: [0.0, 0.0]
  EPSILON: 2.0
  TEMP_OP: "AlwaysOperator"
  INTERVAL: [30, 50]
  INVOLVED_AGENTS: [1, 3]

# TASK_3:
#   EDGE: [3, 4]
#   TYPE: "epsilon_position_closeness_predicate"
#   CENTER: [0.0, 0.0]
#   EPSILON: 2.0
#   TEMP_OP: "AlwaysOperator"
#   INTERVAL: [30, 50]
#   INVOLVED_AGENTS: [3, 4]

# TASK_3:
#   EDGE: [3, 3]
#   TYPE: "go_to_goal_predicate_2d"
#   CENTER: [8.0, 8.0]
#   EPSILON: 2.0
#   TEMP_OP: "AlwaysOperator"
#   INTERVAL: [30, 50]
#   INVOLVED_AGENTS: [3]